### ISSUE TITLE
update MEI-test-set

### ISSUE THREAD

**Issue by rettinghaus** [DDMAL/mei-test-set#7]
Please update the MEI files with sibmei 2.1

**Comment by ahankinson** [comment]
That takes a long time, since the batch processor has to open and close every single Sibelius file. It takes, like 3 hours on my laptop, and I can't use it for anything else.

If there's something specific you see missing or super out-of-date let me know, but I probably won't re-run the entire thing in one go.

**Comment by rettinghaus** [comment]
It's ok, take your time. I was just curious about the results.
